package com.testgroupid;

 
import javafx.scene.Node;

public class TestNode extends Node{
 
        /* 
        this.accessibleHelpProperty();
        this.accessibleRoleDescriptionProperty()
        this.accessibleRoleProperty()
        this.accessibleTextProperty()
        this.addEventFilter(null, null);
        this.addEventHandler(null, null);
        this.applyCss();
        this.autosize();
        this.blendModeProperty()
        this.boundsInLocalProperty()
        this.boundsInParentProperty()
        this.buildEventDispatchChain(null)
        this.cacheHintProperty()
        this.clipProperty()
        this.clone()
        this.computeAreaInScreen()
        this.contains(BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT)
        this.contains(null)
        this.cursorProperty()
        this.depthTestProperty()
        this.disableProperty()
        this.effectProperty()
        this.effectiveNodeOrientationProperty()
        this.equals(getClass())
        this.eventDispatcherProperty()
        this.executeAccessibleAction(null, null);
        this.fireEvent(null);
        this.focusTraversableProperty()
        this.focusedProperty()
        this.getAccessibleHelp()
        this.getAccessibleRole()
        this.getAccessibleRoleDescription()
        this.getAccessibleText()
        this.getBaselineOffset()
        this.getBlendMode()
        this.getBoundsInLocal()
        this.getBoundsInParent()
        this.getCacheHint()
        this.getClass()
        this.getClip()
        this.getContentBias()
        this.getCssMetaData()
        this.getCursor()
        this.getDepthTest()
        this.getEffect()
        this.getEffectiveNodeOrientation()
        this.getEventDispatcher()
        this.getId()
        this.getInitialCursor()
        this.getInitialFocusTraversable()
        this.getInputMethodRequests()
        this.getLayoutBounds()
        this.getLayoutX()
        this.getLayoutY()
        this.getLocalToParentTransform()
        this.getLocalToSceneTransform()
        this.getNodeOrientation()
        this.getOnContextMenuRequested()
        this.getOnDragDetected()
        this.getOnDragDone()
        this.getOnDragDropped()
        this.getOnDragEntered()
        this.getOnDragExited()
        this.getOnDragOver()
        this.getOnInputMethodTextChanged()
        this.getOnKeyPressed()
        this.getOnKeyReleased()
        this.getOnKeyTyped()
        this.getOnMouseClicked()
        this.getOnMouseDragEntered()
        this.getOnMouseDragReleased()
        this.getOnMouseDragOver()
        this.getOnMouseDragReleased() 
        this.getOnMouseDragged()
        this.getOnMouseEntered()
        this.getOnMouseExited()
        this.getOnMouseMoved()
        this.getOnMousePressed()
        this.getOnMouseReleased()
        this.getOnRotate()
        this.getOnRotationFinished()
this.getOnRotationFinished()
this.getOnRotationStarted()
this.getOnScroll()
this.getOnScrollFinished()
this.getOnScrollStarted()
this.getOnSwipeDown() 
this.getOnSwipeLeft()
this.getOnSwipeRight()
this.getOnSwipeRight()
this.getOnSwipeUp()
this.getOnTouchMoved()
this.getOnTouchPressed()
this.getOnTouchReleased()
this.getOnTouchStationary()
this.getOnZoom()
this.getOnZoomFinished()
this.getOnZoomStarted()
this.getOpacity()
this.getParent()
this.getProperties()
this.getPseudoClassStates()
this.getRotate()
this.getRotationAxis()
this.getScaleX()
this.getScaleY()
this.getScaleZ()
this.getScene()
this.getStyle()
this.getStyleClass()
this.getStyleableNode()
this.getStyleableParent()
this.getTransforms()
this.getTranslateX()
this.getTranslateY()
this.getTranslateZ()
this.getTypeSelector()
this.getUserData()
this.getViewOrder()
this.getClassCssMetaData()
this.hasProperties()
this.hashCode()
this.hoverProperty()
this.idProperty()
this.inputMethodRequestsProperty()
this.intersects(BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT)
    this.intersects()
    this.isCache()
this.isDisable()
this.isFocusTraversable()
this.isFocusTraversable()
this.isFocused()
this.isHover()
this.isManaged()
this.isMouseTransparent()
this.isPickOnBounds()
this.isPressed()
this.isResizable()
this.isVisible()

this.layoutBoundsProperty()
this.layoutXProperty()
this.layoutYProperty()
this.localToParent(BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT)
this.localToParentTransformProperty()
this.localToScene(BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, isCache())
this.localToSceneTransformProperty()
this.localToScreen(BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT, BASELINE_OFFSET_SAME_AS_HEIGHT)
this.lookup(getAccessibleHelp())
this.lookupAll(getAccessibleHelp())
this.main();
this.managedProperty()
this.maxHeight(BASELINE_OFFSET_SAME_AS_HEIGHT)
this.maxWidth(BASELINE_OFFSET_SAME_AS_HEIGHT)
this.mouseTransparentProperty()
this.mouseTransparentProperty()
this.nodeOrientationProperty()
this.notify();
this.notifyAccessibleAttributeChanged(null);
this.notifyAll();
  */

        

    


}
